### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by OR13** [did-twit/did-twit#3]
do you compress before base58 encoding?

You might be able to make the create and update payloads smaller by building on top of did-key...where the identifier carries the did document...

here is the approach I took with a did peer implementation:

```
import { Ed25519KeyPair, EdDSA, driver } from '@transmute/did-key-ed25519';

const base64url = require('base64url');
const canonicalize = require('canonicalize');
const R = require('ramda');

const didKeyDocToDidPeerDoc = (didKeyDoc: any) => {
  const didKeyDocString = JSON.stringify(didKeyDoc);
  const didPeerDocString = didKeyDocString.replace(/did:key:/g, 'did:peer:0');
  const didPeerDoc = JSON.parse(didPeerDocString);
  return didPeerDoc;
};

export const generate = async (seed: Buffer) => {
  let key = await Ed25519KeyPair.generate({
    seed,
  });
  const didKeyDoc = driver.keyToDidDoc(key);
  const didPeerDoc = didKeyDocToDidPeerDoc(didKeyDoc);
  return { key, didDoc: didPeerDoc };
};
```

**Comment by glcohen** [comment]
This is a great suggestions, thanks Orie. I am not doing compression, but should. 

I'm still iterating on the first version of the CLI but hope to have some working code out this week. Before then I'll attempt to incorporate your suggestion.

**Comment by glcohen** [comment]
I've updated the spec to incorporate your suggestion. Creating a DID is now really small. Signing a message can still take up to three tweets https://github.com/did-twit/did-twit/blob/master/spec/index.md
